/*CODIGO DO BANCO NA SINTAXE DO MYSQL*/

CREATE DATABASE IF NOT EXISTS BUSCA_CURSOS;
USE BUSCA_CURSOS;

-- Tabela ADMINISTRADOR
CREATE TABLE ADMINISTRADOR
(
    ADM_INT_ID INT NOT NULL AUTO_INCREMENT,
    ADM_STR_NOME VARCHAR(80) NOT NULL,
    ADM_STR_CPF CHAR(11) NOT NULL,
    ADM_STR_SENHA VARCHAR(260) NOT NULL,
    ADM_STR_DATAINSERCAO DATETIME NOT NULL, 
    ADM_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_ADMINISTRADOR_ID PRIMARY KEY (ADM_INT_ID),
    CONSTRAINT UK_CPF_ID UNIQUE (ADM_STR_CPF)
);

ALTER TABLE ADMINISTRADOR 
MODIFY ADM_STR_CPF VARBINARY(255) NOT NULL;

ALTER TABLE ADMINISTRADOR
ADD ADM_STR_EMAIL VARCHAR(120),
ADD CONSTRAINT UK_ADMIN_EMAIL UNIQUE (ADM_STR_EMAIL);


-- Tabela PLATAFORMA
CREATE TABLE PLATAFORMA
(
    PLA_INT_ID INT NOT NULL AUTO_INCREMENT,
    ADM_INT_ID INT NOT NULL,
    PLA_STR_NOME VARCHAR (80) NOT NULL,
    PLA_STR_URL VARCHAR (255) NOT NULL,
    PLA_STR_DESC VARCHAR (350) NOT NULL,
    PLA_INT_QUANTCURSO INT NOT NULL,
    CONSTRAINT PK_PLATAFORMA_ID PRIMARY KEY (PLA_INT_ID),
    CONSTRAINT UK_URL_ID UNIQUE (PLA_STR_URL),
    CONSTRAINT FK_ADMINISTRADOR_PLATAFORMA_ID FOREIGN KEY (ADM_INT_ID)
        REFERENCES ADMINISTRADOR (ADM_INT_ID)
);

-- Tabela CATEGORIA
CREATE TABLE CATEGORIA
(
    CAT_INT_ID INT NOT NULL AUTO_INCREMENT,
    CAT_STR_DESC VARCHAR(350) NOT NULL,
    CAT_STR_INSERCAO DATETIME NOT NULL,
    CONSTRAINT PK_CATEGORIA_ID PRIMARY KEY (CAT_INT_ID)
);

-- Tabela AREACATEGORIA
CREATE TABLE AREACATEGORIA(
    ACA_INT_ID INT NOT NULL AUTO_INCREMENT,
    CAT_INT_ID INT NOT NULL,
    ACA_STR_INSERCAO DATETIME NOT NULL,
    ACA_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_AREACATEGORIA_ID PRIMARY KEY (ACA_INT_ID),
    CONSTRAINT FK_AREACATEGORIA_CATEGORIA_ID FOREIGN KEY (CAT_INT_ID)
        REFERENCES CATEGORIA (CAT_INT_ID)
);

-- Tabela CURSO
CREATE TABLE CURSO
(
    CUR_INT_ID INT NOT NULL AUTO_INCREMENT,
    ACA_INT_ID INT NOT NULL,
    CUR_STR_TITULO VARCHAR (80) NOT NULL,
    CUR_STR_URL VARCHAR(255) NOT NULL,
    CUR_STR_CERTIFICACAO VARCHAR(80) NOT NULL,
    CUR_FLO_QUANTHORA FLOAT NOT NULL, 
    CUR_STR_DESC VARCHAR(350) NOT NULL,
    CUR_STR_DATAINICIO DATETIME NOT NULL,
    CUR_STR_NIVELENSINO VARCHAR(80) NOT NULL,
    CUR_STR_INSERCAO DATETIME NOT NULL,
    CONSTRAINT PK_CURSO_ID PRIMARY KEY (CUR_INT_ID),
    CONSTRAINT FK_CURSO_AREACATEGORIA_ID FOREIGN KEY (ACA_INT_ID)
        REFERENCES AREACATEGORIA (ACA_INT_ID)
);

-- Tabela USUARIO
CREATE TABLE USUARIO
(
    USU_INT_ID INT NOT NULL AUTO_INCREMENT,
    USU_STR_NOME VARCHAR(80) NOT NULL,
    USU_STR_EMAIL VARCHAR(80) NOT NULL,
    USU_STR_SENHA VARCHAR(80) NOT NULL,
    USU_STR_INSERCAO DATETIME NOT NULL,
    USU_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_USUARIO_ID PRIMARY KEY (USU_INT_ID),
    CONSTRAINT UK_EMAIL_ID UNIQUE (USU_STR_EMAIL)
);

-- Tabela FEEDBACK
CREATE TABLE FEEDBACK
(
    FEE_INT_ID INT NOT NULL AUTO_INCREMENT,
    USU_INT_ID INT NOT NULL,
    FEE_STR_TITULO VARCHAR(80) NOT NULL,
    FEE_STR_DESC VARCHAR(250) NOT NULL,
    FEE_STR_AVALIACAO INT NOT NULL,
    FEE_STR_DATAPUBLICACAO DATETIME NOT NULL,
    FEE_STR_COMENTARIO VARCHAR(250) NOT NULL,
    CONSTRAINT PK_FEEDBACK_ID PRIMARY KEY (FEE_INT_ID),
    CONSTRAINT FK_FEEDBACK_USUARIO_ID FOREIGN KEY (USU_INT_ID)
        REFERENCES USUARIO (USU_INT_ID)
);

-- Tabela MENTOR
CREATE TABLE MENTOR
(
    MEN_INT_ID INT NOT NULL AUTO_INCREMENT,
    MEN_STR_NOME VARCHAR(80) NOT NULL,
    MEN_STR_DATAINSERCAO DATETIME NOT NULL,
    MEN_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_MENTOR_ID PRIMARY KEY (MEN_INT_ID)
);

-- Tabela MENTORIA
CREATE TABLE MENTORIA(
    MET_INT_ID INT NOT NULL AUTO_INCREMENT,
    CUR_INT_ID INT NOT NULL,
    PLA_INT_ID INT NOT NULL,
    MEN_INT_ID INT NOT NULL,
    MET_STR_INSERCAO DATETIME NOT NULL,
    MET_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_MENTORIA_ID PRIMARY KEY (MET_INT_ID),
    CONSTRAINT FK_MENTORIA_CURSO_ID FOREIGN KEY (CUR_INT_ID)
        REFERENCES CURSO (CUR_INT_ID),
    CONSTRAINT FK_MENTORIA_PLATAFORMA_ID FOREIGN KEY (PLA_INT_ID)
        REFERENCES PLATAFORMA (PLA_INT_ID),
    CONSTRAINT FK_MENTORIA_MENTOR_ID FOREIGN KEY (MEN_INT_ID)
        REFERENCES MENTOR (MEN_INT_ID)
);

-- Tabela PLATAFORMACURSO
CREATE TABLE PLATAFORMACURSO
(
    PLC_INT_ID INT NOT NULL AUTO_INCREMENT,
    CUR_INT_ID INT NOT NULL,
    PLA_INT_ID INT NOT NULL,
    PLC_STR_DATAINSERCAO DATE NOT NULL, 
    PLC_INT_SITUACAO INT NOT NULL,
    CONSTRAINT PK_PLATAFORMACURSO_ID PRIMARY KEY (PLC_INT_ID),
    CONSTRAINT FK_PLATAFORMACURSO_CURSO_ID FOREIGN KEY (CUR_INT_ID)
        REFERENCES CURSO (CUR_INT_ID),
    CONSTRAINT FK_PLATAFORMACURSO_PLATAFORMA_ID FOREIGN KEY (PLA_INT_ID)
        REFERENCES PLATAFORMA (PLA_INT_ID)
);

-- Tabela HISTORICOUSUARIO
CREATE TABLE HISTORICOUSUARIO(
    HIS_INT_ID INT NOT NULL AUTO_INCREMENT, 
    HIS_STR_INSERCAO DATETIME NOT NULL,
    HIS_STR_DESCRICAO VARCHAR(80) NOT NULL,
    PLC_INT_ID INT NOT NULL,
    USU_INT_ID INT NOT NULL,
    CUR_INT_ID INT NOT NULL,
    ACA_INT_ID INT NOT NULL,
    CONSTRAINT PK_HISTORICOUSUARIO_ID PRIMARY KEY (HIS_INT_ID),
    CONSTRAINT FK_HISTORICOUSUARIO_PLATAFORMACURSO_ID FOREIGN KEY (PLC_INT_ID)
        REFERENCES PLATAFORMACURSO (PLC_INT_ID),
    CONSTRAINT FK_HISTORICOUSUARIO_USUARIO_ID FOREIGN KEY (USU_INT_ID)
        REFERENCES USUARIO (USU_INT_ID),
    CONSTRAINT FK_HISTORICOUSUARIO_CURSO_ID FOREIGN KEY (CUR_INT_ID)
        REFERENCES CURSO (CUR_INT_ID),
    CONSTRAINT FK_HISTORICOUSUARIO_AREACATEGORIA_ID FOREIGN KEY (ACA_INT_ID)
        REFERENCES AREACATEGORIA (ACA_INT_ID)
);

-- tabela favorito
CREATE TABLE FAVORITO (
    FAV_INT_ID INT NOT NULL AUTO_INCREMENT,
    USU_INT_ID INT NOT NULL,
    CUR_INT_ID INT NOT NULL,
    FAV_STR_DATAINSERCAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FAV_INT_ATIVO TINYINT(1) NOT NULL DEFAULT 1, 
    CONSTRAINT PK_FAVORITO_ID PRIMARY KEY (FAV_INT_ID),
    CONSTRAINT UK_USUARIO_CURSO UNIQUE (USU_INT_ID, CUR_INT_ID),
    CONSTRAINT FK_FAVORITO_USUARIO_ID FOREIGN KEY (USU_INT_ID)
        REFERENCES USUARIO (USU_INT_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_FAVORITO_CURSO_ID FOREIGN KEY (CUR_INT_ID)
        REFERENCES CURSO (CUR_INT_ID)
        ON DELETE CASCADE
);

-- tabelas estado, cidade, genero, area_atuacao

CREATE TABLE ESTADO (
    EST_INT_ID INT NOT NULL AUTO_INCREMENT,
    EST_STR_NOME VARCHAR(80) NOT NULL,
    EST_STR_UF CHAR(2) NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (EST_INT_ID)
);
CREATE TABLE CIDADE (
    CID_INT_ID INT NOT NULL AUTO_INCREMENT,
    EST_INT_ID INT NOT NULL,
    CID_STR_NOME VARCHAR(120) NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (CID_INT_ID),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (EST_INT_ID)
        REFERENCES ESTADO (EST_INT_ID)
);
CREATE TABLE GENERO (
    GEN_INT_ID INT NOT NULL AUTO_INCREMENT,
    GEN_STR_DESC VARCHAR(50) NOT NULL,
    CONSTRAINT PK_GENERO PRIMARY KEY (GEN_INT_ID)
);
CREATE TABLE AREA_ATUACAO (
    AAT_INT_ID INT NOT NULL AUTO_INCREMENT,
    AAT_STR_DESC VARCHAR(150) NOT NULL,
    CONSTRAINT PK_AREA_ATUACAO PRIMARY KEY (AAT_INT_ID)
);

-- alteração nas tabelas
ALTER TABLE USUARIO
ADD EST_INT_ID INT NULL,
ADD CID_INT_ID INT NULL,
ADD GEN_INT_ID INT NULL,
ADD AAT_INT_ID INT NULL;

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ESTADO FOREIGN KEY (EST_INT_ID)
    REFERENCES ESTADO (EST_INT_ID);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_CIDADE FOREIGN KEY (CID_INT_ID)
    REFERENCES CIDADE (CID_INT_ID);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_GENERO FOREIGN KEY (GEN_INT_ID)
    REFERENCES GENERO (GEN_INT_ID);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_AREA_ATUACAO FOREIGN KEY (AAT_INT_ID)
    REFERENCES AREA_ATUACAO (AAT_INT_ID);

-- feedback/comentario
ALTER TABLE FEEDBACK
DROP COLUMN FEE_STR_COMENTARIO,
DROP COLUMN FEE_STR_AVALIACAO;

-- tabela comentario
CREATE TABLE COMENTARIO (
    COM_INT_ID INT NOT NULL AUTO_INCREMENT,
    USU_INT_ID INT NOT NULL,
    CUR_INT_ID INT NOT NULL,
    COM_STR_COMENTARIO VARCHAR(350) NOT NULL,
    COM_INT_AVALIACAO INT NOT NULL, 
    COM_STR_DATAPUBLICACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COM_INT_SITUACAO TINYINT(1) NOT NULL DEFAULT 1, 
    CONSTRAINT PK_COMENTARIO PRIMARY KEY (COM_INT_ID),
    CONSTRAINT FK_COMENTARIO_USUARIO FOREIGN KEY (USU_INT_ID)
        REFERENCES USUARIO (USU_INT_ID),
    CONSTRAINT FK_COMENTARIO_CURSO FOREIGN KEY (CUR_INT_ID)
        REFERENCES CURSO (CUR_INT_ID)
);

-- teste vocacional
CREATE TABLE TESTE_VOCACIONAL (
    TES_INT_ID INT NOT NULL AUTO_INCREMENT,
    USU_INT_ID INT NOT NULL,
    CAT_INT_ID INT NOT NULL, 
    TES_INT_PONTUACAO INT NULL,
    TES_STR_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TES_INT_SITUACAO TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT PK_TESTE_VOCACIONAL PRIMARY KEY (TES_INT_ID),
    CONSTRAINT FK_TESTE_VOCACIONAL_USUARIO FOREIGN KEY (USU_INT_ID)
        REFERENCES USUARIO (USU_INT_ID),
    CONSTRAINT FK_TESTE_VOCACIONAL_CATEGORIA FOREIGN KEY (CAT_INT_ID)
        REFERENCES CATEGORIA (CAT_INT_ID)
);

-- tabela comentario_curso particionada por ano
CREATE TABLE COMENTARIO_CURSO (
    COM_INT_ID INT NOT NULL AUTO_INCREMENT,
    CUR_INT_ID INT NOT NULL,
    USU_INT_ID INT NOT NULL,
    COM_TXT_TEXTO TEXT NOT NULL,
    COM_INT_AVALIACAO INT NOT NULL,
    COM_DATA DATETIME NOT NULL,
    PRIMARY KEY (COM_INT_ID, COM_DATA)
)
PARTITION BY RANGE (YEAR(COM_DATA)) (
    PARTITION p2024 VALUES LESS THAN (2025),
    PARTITION p2025 VALUES LESS THAN (2026),
    PARTITION p2026 VALUES LESS THAN (2027)
);


-- //  -- Triggers -- // --

CREATE TABLE LOG_CURSO (
    LOG_INT_ID INT NOT NULL AUTO_INCREMENT,
    CUR_INT_ID INT NOT NULL,
    LOG_STR_ACAO VARCHAR(20) NOT NULL, 
    LOG_STR_INFO JSON,
    LOG_STR_DATA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LOG_CURSO_ID PRIMARY KEY (LOG_INT_ID)
);

CREATE TRIGGER TRG_CURSO_INSERT
AFTER INSERT ON CURSO
FOR EACH ROW
BEGIN
    INSERT INTO LOG_CURSO (CUR_INT_ID, LOG_STR_ACAO, LOG_STR_INFO)
    VALUES (
        NEW.CUR_INT_ID,
        'INSERT',
        JSON_OBJECT(
            'titulo', NEW.CUR_STR_TITULO,
            'descricao', NEW.CUR_STR_DESC,
            'url', NEW.CUR_STR_URL
        )
    );
END;

--

CREATE TRIGGER TRG_CURSO_UPDATE
AFTER UPDATE ON CURSO
FOR EACH ROW
BEGIN
    INSERT INTO LOG_CURSO (CUR_INT_ID, LOG_STR_ACAO, LOG_STR_INFO)
    VALUES (
        NEW.CUR_INT_ID,
        'UPDATE',
        JSON_OBJECT(
            'antes', JSON_OBJECT(
                'titulo', OLD.CUR_STR_TITULO,
                'descricao', OLD.CUR_STR_DESC,
                'url', OLD.CUR_STR_URL
            ),
            'depois', JSON_OBJECT(
                'titulo', NEW.CUR_STR_TITULO,
                'descricao', NEW.CUR_STR_DESC,
                'url', NEW.CUR_STR_URL
            )
        )
    );
END;

-- //  -- views -- // --
CREATE OR REPLACE VIEW vw_recomendacao_por_teste AS
SELECT 
    tv.USU_INT_ID,
    tv.CAT_INT_ID AS categoria_resultado_id,
    cat.CAT_STR_DESC AS categoria_resultado,
    
    ac.ACA_INT_ID AS area_categoria_id,
    ac.ACA_INT_SITUACAO AS area_situacao,
    
    c.CUR_INT_ID AS curso_id,
    c.CUR_STR_TITULO AS curso_titulo,
    c.CUR_STR_DESC AS curso_descricao,
    c.CUR_STR_URL AS curso_url,
    c.CUR_STR_CERTIFICACAO AS curso_certificacao,
    c.CUR_FLO_QUANTHORA AS curso_horas,
    c.CUR_STR_NIVELENSINO AS curso_nivel,
    c.CUR_STR_DATAINICIO AS curso_data_inicio,
    
    pc.PLA_INT_ID AS plataforma_id,
    p.PLA_STR_NOME AS plataforma_nome,
    p.PLA_STR_URL AS plataforma_url

FROM TESTE_VOCACIONAL tv
JOIN CATEGORIA cat 
    ON cat.CAT_INT_ID = tv.CAT_INT_ID

JOIN AREACATEGORIA ac
    ON ac.CAT_INT_ID = cat.CAT_INT_ID
    AND ac.ACA_INT_SITUACAO = 1   

JOIN CURSO c
    ON c.ACA_INT_ID = ac.ACA_INT_ID

LEFT JOIN PLATAFORMACURSO pc
    ON pc.CUR_INT_ID = c.CUR_INT_ID
    AND pc.PLC_INT_SITUACAO = 1   

LEFT JOIN PLATAFORMA p
    ON p.PLA_INT_ID = pc.PLA_INT_ID;

--
CREATE VIEW vw_media_avaliacao_curso AS
SELECT 
    c.CUR_INT_ID,
    c.CUR_STR_TITULO,
    AVG(co.COM_INT_AVALIACAO) AS media,
    COUNT(co.COM_INT_ID) AS totalAvaliacoes
FROM CURSO c
LEFT JOIN COMENTARIO co ON co.CUR_INT_ID = c.CUR_INT_ID AND co.COM_INT_SITUACAO = 1
GROUP BY c.CUR_INT_ID;

CREATE OR REPLACE VIEW vw_qtd_cursos_plataforma AS
SELECT 
    p.PLA_INT_ID,
    p.PLA_STR_NOME,
    p.PLA_STR_URL,
    COUNT(pc.CUR_INT_ID) AS total_cursos
FROM PLATAFORMA p
LEFT JOIN PLATAFORMACURSO pc 
    ON pc.PLA_INT_ID = p.PLA_INT_ID 
    AND pc.PLC_INT_SITUACAO = 1
GROUP BY 
    p.PLA_INT_ID,
    p.PLA_STR_NOME,
    p.PLA_STR_URL;

-- FUNCOES --
DELIMITER $$

CREATE FUNCTION FN_CATEGORIA_RECOMENDADA(p_usuario INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE v_cat INT;

    SELECT CAT_INT_ID
    INTO v_cat
    FROM TESTE_VOCACIONAL
    WHERE USU_INT_ID = p_usuario
    ORDER BY TES_INT_PONTUACAO DESC, TES_STR_DATA DESC
    LIMIT 1;

    RETURN v_cat;
END$$

DELIMITER ;

SELECT 
    CUR.*
FROM CURSO CUR
JOIN AREACATEGORIA ACA ON CUR.ACA_INT_ID = ACA.ACA_INT_ID
WHERE ACA.CAT_INT_ID = FN_GET_CATEGORIA_RECOMENDADA(3);

--

DELIMITER $$

CREATE FUNCTION fn_buscar_cursos_por_area(p_area VARCHAR(100))
RETURNS TEXT
DETERMINISTIC
BEGIN
    DECLARE lista_cursos TEXT;

    SELECT GROUP_CONCAT(CUR_STR_NOME SEPARATOR ', ')
    INTO lista_cursos
    FROM CURSO
    WHERE CUR_STR_AREA = p_area;

    RETURN lista_cursos;
END$$

DELIMITER ;

SELECT fn_buscar_cursos_por_area('Tecnologia');


--Indices
-- Índices para PLATAFORMA
CREATE INDEX IDX_PLATAFORMA_ADM_ID ON PLATAFORMA (ADM_INT_ID);

-- Índices para AREACATEGORIA
CREATE INDEX IDX_AREACATEGORIA_CAT_ID ON AREACATEGORIA (CAT_INT_ID);

-- Índices para CURSO
CREATE INDEX IDX_CURSO_ACA_ID ON CURSO (ACA_INT_ID);

-- Índices para FEEDBACK
CREATE INDEX IDX_FEEDBACK_USU_ID ON FEEDBACK (USU_INT_ID);

-- Índices para MENTORIA
CREATE INDEX IDX_MENTORIA_CURSO_ID ON MENTORIA (CUR_INT_ID);
CREATE INDEX IDX_MENTORIA_PLA_ID ON MENTORIA (PLA_INT_ID);
CREATE INDEX IDX_MENTORIA_MEN_ID ON MENTORIA (MEN_INT_ID);

-- Índices para PLATAFORMACURSO
CREATE INDEX IDX_PLC_CURSO_ID ON PLATAFORMACURSO (CUR_INT_ID);
CREATE INDEX IDX_PLC_PLA_ID ON PLATAFORMACURSO (PLA_INT_ID);

-- Índices para HISTORICOUSUARIO
CREATE INDEX IDX_HIS_PLC_ID ON HISTORICOUSUARIO (PLC_INT_ID);
CREATE INDEX IDX_HIS_USU_ID ON HISTORICOUSUARIO (USU_INT_ID);
CREATE INDEX IDX_HIS_CURSO_ID ON HISTORICOUSUARIO (CUR_INT_ID);
CREATE INDEX IDX_HIS_ACA_ID ON HISTORICOUSUARIO (ACA_INT_ID);

-- Índices para FAVORITO
CREATE INDEX IDX_FAV_USU_ID ON FAVORITO (USU_INT_ID);
CREATE INDEX IDX_FAV_CUR_ID ON FAVORITO (CUR_INT_ID);

-- Índices para USUARIO (relacionamentos)
CREATE INDEX IDX_USUARIO_ESTADO ON USUARIO (EST_INT_ID);
CREATE INDEX IDX_USUARIO_CIDADE ON USUARIO (CID_INT_ID);
CREATE INDEX IDX_USUARIO_GENERO ON USUARIO (GEN_INT_ID);
CREATE INDEX IDX_USUARIO_AAT_ON ON USUARIO (AAT_INT_ID);

-- Índices para COMENTARIO
CREATE INDEX IDX_COM_USU_ID ON COMENTARIO (USU_INT_ID);
CREATE INDEX IDX_COM_CUR_ID ON COMENTARIO (CUR_INT_ID);

-- Índices para TESTE_VOCACIONAL
CREATE INDEX IDX_TES_USU_ID ON TESTE_VOCACIONAL (USU_INT_ID);
CREATE INDEX IDX_TES_CAT_ID ON TESTE_VOCACIONAL (CAT_INT_ID);
